version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user/acebook-node-template
hooks:
  BeforeInstall:
    - location: scripts/install_dependencies.sh
      timeout: 300
      runas: root
  ApplicationStart:
    - location: scripts/start_mongodb.sh
      timeout: 300
    - location: scripts/start_server.sh
      timeout: 300
      runas: root
